version: '3.9'

services:
  app:
    build: .
    container_name: nest_app
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nest_prisma_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: 'no'
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres_data:
